// <auto-generated />
namespace forCrowd.Backbone.DataObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V_0_4_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V_0_4_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131901573_V_0_4_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
